# NUMPY PROGRAM PRECTICE

## Weather Data Analysis 🌦️

In [2]:
import numpy as np

In [3]:
temps = np.array([32, 35, 28, 30, 31, 29, 33])

In [4]:
print(temps * 9/5 +32)

[89.6 95.  82.4 86.  87.8 84.2 91.4]


In [5]:
print(np.mean(temps))

31.142857142857142


In [6]:
print(np.min(temps))

28


In [7]:
print(np.max(temps))

35


## E-commerce Sales Analysis 🛒 ##

In [9]:
sales = np.array([12, 15, 9, 14, 11, 18, 16, 13, 17, 19])

In [10]:
print(np.sum(sales))

144


In [11]:
print(np.mean(sales))

14.4


In [14]:
print(np.size(sales[sales > 15]))
print(sales[sales > 15])

4
[18 16 17 19]


In [15]:
print(np.sort(sales))

[ 9 11 12 13 14 15 16 17 18 19]


## Image Processing Basics 🖼️ ##

In [16]:
image = np.array([[100, 150, 200], [50, 120, 180], [30, 80, 160]])

In [17]:
brightness = 50
print(image + brightness)

[[150 200 250]
 [100 170 230]
 [ 80 130 210]]


In [18]:
print(np.mean(image))

118.88888888888889


In [20]:
print(image[1,:])

[ 50 120 180]


In [21]:
print(image[:,0])

[100  50  30]


## Stock Market Data 📈 ##

In [2]:
import numpy as np

In [3]:
stocks = np.array([1200, 1250, 1220, 1300, 1280])

In [5]:
print(stocks / 100)

[12.  12.5 12.2 13.  12.8]


In [13]:
print(np.argmax(stocks) + 1)

4


In [17]:
arr_average = np.mean(stocks)
print(arr_average)

1250.0


In [18]:
print(stocks - arr_average)

[-50.   0. -30.  50.  30.]


##  Student Marks Processing 🎓 ##

In [2]:
import numpy as np

In [3]:
marks = np.array([[80, 90, 85], [70, 75, 78], [88, 92, 95], [60, 65, 70], [90, 85, 88]])

In [5]:
print(np.sum(marks,axis = 1))

[255 223 275 195 263]


In [6]:
print(np.mean(marks,axis = 0))

[77.6 81.4 83.2]


In [20]:
scored_student = np.all(marks > 84, axis = 1)

In [21]:
print(scored_student)

[False False  True False  True]


In [22]:
score = np.where(scored_student)[0] + 1

In [23]:
print(score)

[3 5]


## Customer Review Analysis ⭐ ##

In [25]:
ratings = np.array([4, 5, 2, 3, 5, 1])

In [26]:
print(np.mean(ratings))

3.3333333333333335


In [32]:
print(np.sum(ratings == 5) / len(ratings) * 100)

33.33333333333333


In [36]:
print(np.sum(ratings <= 3))

3


In [39]:
satisfaction =  np.where(ratings == 5,"Excellent",
                np.where(ratings == 4, "Good",
                np.where(ratings == 3, "Average",
                np.where(ratings == 2, "Poor","Terrible"))))
print(satisfaction)

['Good' 'Excellent' 'Poor' 'Average' 'Excellent' 'Terrible']


## Fitness Tracker 📊 ##

In [52]:
steps = np.array([8000, 7500, 8200, 7800, 6000, 10000, 9500])

In [53]:
print(np.sum(steps))

66500


In [54]:
print(np.mean(steps))

8312.5


In [55]:
print(np.sum(steps < 8000))

3


In [59]:
print(np.argmax(steps) + 1)

6
