In [1]:
import numpy as np

In [5]:
list1 = [1,2,3,4,5,6,7]
arr = np.array(list1)

In [6]:
print(arr)

[1 2 3 4 5 6 7]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr = np.zeros(5)

In [10]:
print(arr)

[0. 0. 0. 0. 0.]


In [12]:
arr = np.zeros([5,5])
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
arr = np.zeros([3,3,3])
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
arr = np.ones(5)

In [15]:
print(arr)

[1. 1. 1. 1. 1.]


In [16]:
arr = np.ones([2,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
arr = np.full([2,2],6)
print(arr)

[[6 6]
 [6 6]]


In [18]:
arr = np.array([[1,3,2],[5,4,6]])
print(arr)

[[1 3 2]
 [5 4 6]]


In [25]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [26]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1, 10,5)

array([1, 6])

In [40]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
arr = np.full([3,3],7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [45]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [51]:
print(arr[2,:])

[70 80 90]


In [50]:
print(arr[:,2])

[30 60 90]


In [52]:
arr = np.array([5, 15, 25, 35, 45])

In [53]:
print(arr.sum())

125


In [54]:
print(arr.mean())

25.0


In [55]:
print(arr.max())

45


In [60]:
print(arr.dtype)

int64


In [63]:
print(arr.dtype)

int64


In [97]:
arr = np.arange(1,17)

In [98]:
arr_reshaped = arr.reshape(4,4)

In [99]:
print(arr_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [92]:
print(arr_reshaped.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [100]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.vstack((a, b)))  # Stack vertically
print(np.hstack((a, b)))  # Stack horizontally

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
