In [1]:
import numpy as np

In [5]:
list1 = [1,2,3,4,5,6,7]
arr = np.array(list1)

In [6]:
print(arr)

[1 2 3 4 5 6 7]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr = np.zeros(5)

In [10]:
print(arr)

[0. 0. 0. 0. 0.]


In [12]:
arr = np.zeros([5,5])
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
arr = np.zeros([3,3,3])
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
arr = np.ones(5)

In [15]:
print(arr)

[1. 1. 1. 1. 1.]


In [16]:
arr = np.ones([2,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
arr = np.full([2,2],6)
print(arr)

[[6 6]
 [6 6]]


In [18]:
arr = np.array([[1,3,2],[5,4,6]])
print(arr)

[[1 3 2]
 [5 4 6]]


In [25]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [26]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1, 10,5)

array([1, 6])

In [40]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
arr = np.full([3,3],7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [45]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [51]:
print(arr[2,:])

[70 80 90]


In [50]:
print(arr[:,2])

[30 60 90]


In [52]:
arr = np.array([5, 15, 25, 35, 45])

In [53]:
print(arr.sum())

125


In [54]:
print(arr.mean())

25.0


In [55]:
print(arr.max())

45


In [60]:
print(arr.dtype)

int64


In [63]:
print(arr.dtype)

int64


In [97]:
arr = np.arange(1,17)

In [98]:
arr_reshaped = arr.reshape(4,4)

In [99]:
print(arr_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [92]:
print(arr_reshaped.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [100]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.vstack((a, b)))  # Stack vertically
print(np.hstack((a, b)))  # Stack horizontally

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [8]:
import numpy as np

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr[arr > 20])

[30 40 50 60 70 80 90]


In [23]:
arr = np.random.randint(1,100,(2,2))

In [24]:
print(arr)

[[48 44]
 [25 47]]


In [32]:
np.random.seed(42)


In [30]:
arr = np.random.randint(1,100,(2,2))

In [31]:
print(arr)

[[52 93]
 [15 72]]


In [33]:
scaral = 7
print(arr + scaral)

[[ 59 100]
 [ 22  79]]


In [49]:
arr_pr1 = np.arange(1,101)

In [50]:
print(arr_pr1)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [51]:
arr_pr2 = arr_pr1.reshape(10,10)


In [52]:
print(arr_pr2)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [85]:
print(np.sum(arr_pr2[1:6],axis=1))

[155 255 355 455 555]


In [93]:
print(arr_pr2[arr_pr2 % 7 == 0])

[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
