# NUMPY PROGRAM PRECTICE

## Weather Data Analysis 🌦️

In [2]:
import numpy as np

In [3]:
temps = np.array([32, 35, 28, 30, 31, 29, 33])

In [4]:
print(temps * 9/5 +32)

[89.6 95.  82.4 86.  87.8 84.2 91.4]


In [5]:
print(np.mean(temps))

31.142857142857142


In [6]:
print(np.min(temps))

28


In [7]:
print(np.max(temps))

35


## E-commerce Sales Analysis 🛒 ##

In [9]:
sales = np.array([12, 15, 9, 14, 11, 18, 16, 13, 17, 19])

In [10]:
print(np.sum(sales))

144


In [11]:
print(np.mean(sales))

14.4


In [14]:
print(np.size(sales[sales > 15]))
print(sales[sales > 15])

4
[18 16 17 19]


In [15]:
print(np.sort(sales))

[ 9 11 12 13 14 15 16 17 18 19]


## Image Processing Basics 🖼️ ##

In [16]:
image = np.array([[100, 150, 200], [50, 120, 180], [30, 80, 160]])

In [17]:
brightness = 50
print(image + brightness)

[[150 200 250]
 [100 170 230]
 [ 80 130 210]]


In [18]:
print(np.mean(image))

118.88888888888889


In [20]:
print(image[1,:])

[ 50 120 180]


In [21]:
print(image[:,0])

[100  50  30]


## Stock Market Data 📈 ##

In [2]:
import numpy as np

In [3]:
stocks = np.array([1200, 1250, 1220, 1300, 1280])

In [5]:
print(stocks / 100)

[12.  12.5 12.2 13.  12.8]


In [13]:
print(np.argmax(stocks) + 1)

4


In [17]:
arr_average = np.mean(stocks)
print(arr_average)

1250.0


In [18]:
print(stocks - arr_average)

[-50.   0. -30.  50.  30.]


##  Student Marks Processing 🎓 ##

In [2]:
import numpy as np

In [3]:
marks = np.array([[80, 90, 85], [70, 75, 78], [88, 92, 95], [60, 65, 70], [90, 85, 88]])

In [5]:
print(np.sum(marks,axis = 1))

[255 223 275 195 263]


In [6]:
print(np.mean(marks,axis = 0))

[77.6 81.4 83.2]


In [20]:
scored_student = np.all(marks > 84, axis = 1)

In [21]:
print(scored_student)

[False False  True False  True]


In [22]:
score = np.where(scored_student)[0] + 1

In [23]:
print(score)

[3 5]


## Customer Review Analysis ⭐ ##

In [25]:
ratings = np.array([4, 5, 2, 3, 5, 1])

In [26]:
print(np.mean(ratings))

3.3333333333333335


In [32]:
print(np.sum(ratings == 5) / len(ratings) * 100)

33.33333333333333


In [36]:
print(np.sum(ratings <= 3))

3


In [39]:
satisfaction =  np.where(ratings == 5,"Excellent",
                np.where(ratings == 4, "Good",
                np.where(ratings == 3, "Average",
                np.where(ratings == 2, "Poor","Terrible"))))
print(satisfaction)

['Good' 'Excellent' 'Poor' 'Average' 'Excellent' 'Terrible']


## Fitness Tracker 📊 ##

In [52]:
steps = np.array([8000, 7500, 8200, 7800, 6000, 10000, 9500])

In [53]:
print(np.sum(steps))

66500


In [54]:
print(np.mean(steps))

8312.5


In [55]:
print(np.sum(steps < 8000))

3


In [59]:
print(np.argmax(steps) + 1)

6


## Banking Transactions 💰 ##

In [2]:
import numpy as np

In [3]:
transactions = np.array([5000, -2000, 3000, -1000, 7000, -500, 2000])

In [4]:
print(np.sum(transactions))

13500


In [5]:
print(np.mean(transactions))

1928.5714285714287


In [11]:
print(np.sum(transactions < 0))

3


In [12]:
print(transactions[transactions > 0])

[5000 3000 7000 2000]


##  Machine Learning Data Scaling ⚙️ ##

In [13]:
data = np.array([25, 50, 75, 100, 125])

In [14]:
min_data = np.min(data)

In [15]:
max_data = np.max(data)

In [16]:
answer = (data - min_data) / (max_data -min_data)

In [17]:
print(answer)

[0.   0.25 0.5  0.75 1.  ]


In [20]:
z = data - np.mean(data) / np.std(data)

In [21]:
print(z)

[ 22.87867966  47.87867966  72.87867966  97.87867966 122.87867966]


## FINAL CHALLENGE: AI Data Preparation 🤖 ##

In [40]:
np.random.seed(45)

In [41]:
data = np.random.randint(1,500,100)

In [42]:
print(data)

[460 415 132 381  33  96 446 214 164  69 378 121  16  66 399 310  58 375
 457 216 303 265 182 397 419 381  25 269  18 487 197 111 127 159 313 271
 491  37 288  87 421 186 190 208 402   7 365  43  12 233 137  50  78 380
 204 254 320  43  55 401 245 153 368 497 234  96 320  99 279 104  28 289
 401 204 187 243 317 106 499 311 481 378 199 161 489 249 145 316 487  93
 384 312  89   6 252  82 478 464 452  56]


In [43]:
mean = np.mean(data)

In [44]:
median = np.median(data)

In [45]:
std = np.std(data)

In [47]:
print(f" Mean = {mean} \n Median = {median} \n standerd deviation = {std}")

 Mean = 241.75 
 Median = 238.5 
 standerd deviation = 149.18407254127365


In [52]:
print(data[data > mean])

[460 415 381 446 378 399 310 375 457 303 265 397 419 381 269 487 313 271
 491 288 421 402 365 380 254 320 401 245 368 497 320 279 289 401 243 317
 499 311 481 378 489 249 316 487 384 312 252 478 464 452]


In [54]:
new_arr = data.reshape(10,10)

In [55]:
print(new_arr)

[[460 415 132 381  33  96 446 214 164  69]
 [378 121  16  66 399 310  58 375 457 216]
 [303 265 182 397 419 381  25 269  18 487]
 [197 111 127 159 313 271 491  37 288  87]
 [421 186 190 208 402   7 365  43  12 233]
 [137  50  78 380 204 254 320  43  55 401]
 [245 153 368 497 234  96 320  99 279 104]
 [ 28 289 401 204 187 243 317 106 499 311]
 [481 378 199 161 489 249 145 316 487  93]
 [384 312  89   6 252  82 478 464 452  56]]


In [56]:
print(np.sum(new_arr, axis=1))

[2410 2396 2746 2081 2067 1922 2395 2585 2998 2575]


In [57]:
print(new_arr[new_arr % 5 == 0])

[460 415 310 375 265  25 190 365  50 380 320  55 245 320 145]
