# NUMPY PROGRAM PRECTICE

## Weather Data Analysis 🌦️

In [2]:
import numpy as np

In [3]:
temps = np.array([32, 35, 28, 30, 31, 29, 33])

In [4]:
print(temps * 9/5 +32)

[89.6 95.  82.4 86.  87.8 84.2 91.4]


In [5]:
print(np.mean(temps))

31.142857142857142


In [6]:
print(np.min(temps))

28


In [7]:
print(np.max(temps))

35


## E-commerce Sales Analysis 🛒 ##

In [9]:
sales = np.array([12, 15, 9, 14, 11, 18, 16, 13, 17, 19])

In [10]:
print(np.sum(sales))

144


In [11]:
print(np.mean(sales))

14.4


In [14]:
print(np.size(sales[sales > 15]))
print(sales[sales > 15])

4
[18 16 17 19]


In [15]:
print(np.sort(sales))

[ 9 11 12 13 14 15 16 17 18 19]


## Image Processing Basics 🖼️ ##

In [16]:
image = np.array([[100, 150, 200], [50, 120, 180], [30, 80, 160]])

In [17]:
brightness = 50
print(image + brightness)

[[150 200 250]
 [100 170 230]
 [ 80 130 210]]


In [18]:
print(np.mean(image))

118.88888888888889


In [20]:
print(image[1,:])

[ 50 120 180]


In [21]:
print(image[:,0])

[100  50  30]


## Stock Market Data 📈 ##